### PR TITLE
Add tests and fix external links

### LINKED ISSUE #24: This changes query params as well
I installed Jetpack social sharing to one of our sites. If this plugin was in use the twitter sharing changed the query params of url from ```mysite.com``` always into ```mysite.seravo.fi```.

I tracked it down to wp-redirect filter which returned correct host name but changed query_params.

See the query params in below:

```
$ curl -I -H 'Pragma: no-cache' "http://mysite.com/kohteet/example-t2/?share=twitter&nb=1"
HTTP/1.1 302 Found
Server: nginx
Date: Thu, 18 Jun 2015 17:25:04 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: PHPSESSID=n5uvbif5njam7il6bqgjt2opm1; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Pingback: http://mysite.com/xmlrpc.php
Location: https://twitter.com/intent/tweet?via=Test&text=Testing&url=http%3A%2F%mysite.seravo.fi%2Fkohteet%example-t2%2F
```

### PR DESCRIPTION
**Pull request by onnimonni**
This fixes #24 and adds some tests for the url rewriting. I also replaced regex replaces to faster alternative and better suited for this easy replacements.

### CODE REVIEW

**Comment by ottok** [comment]
Scary big rewrites and so many commits with vague commit messages, but as tests are included let's pull anyway.

File: https-domain-alias.php [hunk 1]
```diff
@@ -344,6 +321,62 @@ function htsda_https_domain_alias_readme() {
...
 /*
+ * Helper: Rewrite url if it's pointing to this site
+ * 
+ * @param string    well formed url     
+ * @param array    domains of the site
+ * (optional)@param string    ssl secured domain alias of the site
+ */
+function hstda_rewrite_url($url,$domains,$domainAlias=NULL) {
+  $parts = parse_url($url);
+  error_log("HSTDA url:".$url,0);
```
Comment (ottok) [inline https-domain-alias.php]: please comment out or remove debug line

Comment (onnimonni) [inline https-domain-alias.php]: Done!
